[package]
name = "contract"
version = "0.1.0"
authors = ["Kochavalabs"]
edition = "2018"

[dependencies]
mazzaroth-rs = "0.8.0"
mazzaroth-rs-derive = "0.8.0"
xdr-rs-serialize = "0.3.0"
xdr-rs-serialize-derive = "0.3.0"
mazzaroth-xdr = "0.8.1"
json = "0.12.0"
